[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = "0.8.20"
evm_version = 'paris'
optimizer = true
optimizer_runs = 800
via_ir = false

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true 